on: [push]

name: Linter, SCSS

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: stylelint
        uses: actions-hub/stylelint@master
