on: [push]

name: Tests

jobs:
  run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6-alpine
        ports: ['5432:5432']
        env:
          PGUSER: postgres
          PGPASSWORD: password
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install system libraries
        run: |
          sudo apt-get -y install libpq-dev

        # This uses .ruby-version file to set the version
      - name: Set up Ruby 2.6
        uses: eregon/use-ruby-action@master

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install Ruby gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Configure database
        env:
          PGUSER: postgres
          PGPASSWORD: password
        run: |
          bundle exec rails db:create

      - name: Run tests
        env:
          PGUSER: postgres
          PGPASSWORD: password
        run: |
          bundle exec rspec
